name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/ha-threedy-card-prusalink/ha-threedy-card-prusalink
          yarn install
          yarn run build

      # Upload build file to the releas as an asset.
      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./dist/threedy-card-prusalink.js text/javascript
